"""`reports/replication/tables.md`: the re-estimated tables next to the published ones."""

from __future__ import annotations

import json
from typing import Any

import numpy as np

from airline_delays.estimation.compare import STAT_LABELS
from airline_delays.estimation.specification import COEF_LABEL, COEF_ORDER

TABLE_TITLES = {
    "table2": "Table 2 - Descriptive statistics",
    "table3": "Table 3 - Estimation results (2SGMM)",
    "table4": "Table 4 - Robustness checks (2SGMM)",
    "table5": "Table 5 - Estimation results (LIML)",
    "table6": "Table 6 - Estimation results (OLS)",
    "table7": "Table 7 - Estimation results (departures)",
}

#: Row labels for the report: the regressor labels plus the two regressands of Table 2.
ROW_LABEL = COEF_LABEL | {"fsc_oddsarr": "ODDS", "fsc_minsarr": "MINS"}


def _fmt(value: Any, digits: int = 4) -> str:
    if value is None or (isinstance(value, float) and not np.isfinite(value)):
        return "--"
    if isinstance(value, bool):
        return "yes" if value else "no"
    if isinstance(value, int):
        return f"{value:,}"
    return f"{value:.{digits}f}"


def write_markdown(results: dict[str, Any], summary: dict[str, Any], grid: dict[str, Any]) -> str:
    """Published x replicated x difference, table by table."""
    meta = results["meta"]
    panel = meta.get("panel", {})
    lines: list[str] = [
        "# Replication of Tables 2-7 -- published against re-estimated",
        "",
        (
            f"Generated by `airline-delays estimate` in {meta['seconds']:.1f} s on the article's "
            f"estimation panel (`{panel.get('path', 'data/analysis/article_panel_route_month.parquet')}`, "
            f"{_fmt(panel.get('rows'))} route-months, curated from the authors' final base of "
            f"{panel.get('source_header_timestamp', 'December 2015')[:10]}). Published values are "
            "parsed from the article by `src/airline_delays/estimation/published.py` into "
            "`src/airline_delays/estimation/published.json`; no number here is typed by hand."
        ),
        "",
        (
            f"HAC: Bartlett kernel, bandwidth {meta['bandwidth']} in the `linearmodels` convention "
            f"(= Stata `bw(5)`), finite-sample correction {'on' if meta['debiased'] else 'off'}, "
            f"seasonality dummies {'in' if meta['with_seasonality'] else 'out'}."
        ),
        "",
        "## Scorecard",
        "",
        (
            "`diff/s.e.` is the difference between the re-estimated and the published "
            "coefficient, measured in *published* standard errors -- the column that decides "
            "whether an estimate is materially different."
        ),
        "",
        (
            "| Table | coefficients | signs equal | within 0.5 s.e. | median diff/s.e. | "
            "max diff/s.e. | median s.e. ratio |"
        ),
        "|---|---:|---:|---:|---:|---:|---:|",
    ]
    for name, values in summary.items():
        if name not in TABLE_TITLES or name == "table2":
            continue
        lines.append(
            f"| {TABLE_TITLES[name]} | {values['n_coefficients']} | "
            f"{values['sign_agreement']}/{values['n_coefficients']} | "
            f"{values['within_half_se']}/{values['n_coefficients']} "
            f"({values['within_half_se_share'] * 100:.0f}%) | "
            f"{values['median_difference_in_se']:.3f} | "
            f"{values['max_difference_in_se']:.3f} | "
            f"{values['median_se_ratio']:.3f} |"
        )

    hhi = summary.get("hhi_sign_inversions", {})
    if hhi.get("available"):
        lines += [
            "",
            "### HHI sign inversion, OLS (Table 6) against 2SGMM (Table 3)",
            "",
            (
                f"{hhi['n_comparisons']} comparisons "
                f"({len(hhi['variables'])} HHI terms x "
                f"{hhi['n_comparisons'] // len(hhi['variables'])} columns). An inversion "
                f"occurs in **{hhi['n_inverted_published']}** of them in the published "
                f"tables and in **{hhi['n_inverted_replicated']}** here; the published "
                f"inversion replicates in **{hhi['n_inversion_replicates']}** "
                f"(columns {', '.join(hhi['columns_with_inversion']) or 'none'}). "
                f"Replication and article agree on *whether* the sign flips in "
                f"**{hhi['n_pattern_agrees']}** of {hhi['n_comparisons']}."
            ),
            "",
            (
                "| Column | Regressand | Variable | OLS pub | 2SGMM pub | inverted pub | "
                "OLS rep | 2SGMM rep | inverted rep |"
            ),
            "|---|---|---|---:|---:|---|---:|---:|---|",
        ]
        for cell in hhi["detail"]:
            lines.append(
                f"| ({cell['column']}) | {cell['regressand']} | "
                f"`{cell['variable']}` | "
                f"{_fmt(cell['published']['ols'])} | {_fmt(cell['published']['gmm'])} | "
                f"{_fmt(cell['published']['inverted'])} | "
                f"{_fmt(cell['replicated']['ols'])} | {_fmt(cell['replicated']['gmm'])} | "
                f"{_fmt(cell['replicated']['inverted'])} |"
            )

    table2_block = results.get("table2")
    if table2_block:
        comparison = table2_block["comparison"]
        lines += [
            "",
            f"## {TABLE_TITLES['table2']}",
            "",
            (
                f"Sample: "
                f"{_fmt(table2_block['replicated']['sample'].get('n_after_singleton_cut'))} "
                f"observations, {table2_block['replicated']['sample'].get('routes')} routes. "
                f"Correlation triangle: {comparison['n_correlations']} cells compared, median "
                f"absolute difference "
                f"{_fmt(comparison['median_abs_correlation_difference'], 3)}, maximum "
                f"{_fmt(comparison['max_abs_correlation_difference'], 3)}."
            ),
            "",
            (
                "| Variable | mean pub | mean rep | s.d. pub | s.d. rep | min pub | min rep | "
                "max pub | max rep |"
            ),
            "|---|---:|---:|---:|---:|---:|---:|---:|---:|",
        ]
        for name in table2_block["published"]["variables"]:
            cells = [ROW_LABEL.get(name, name)]
            for statistic in ("mean", "sd", "min", "max"):
                entry = comparison["univariate"].get(statistic, {}).get(name, {})
                cells += [_fmt(entry.get("published"), 2), _fmt(entry.get("replicated"), 4)]
            lines.append("| " + " | ".join(cells) + " |")

    for name, module_block in results.items():
        if name in {"meta", "table2"} or "comparison" not in module_block:
            continue
        lines += ["", f"## {TABLE_TITLES[name]}", ""]
        columns = module_block["comparison"]
        header = list(columns)
        lines += [
            "Coefficients, with published standard errors in brackets.",
            "",
            "| Variable | "
            + " | ".join(f"({key}) pub | ({key}) rep | ({key}) diff/s.e." for key in header)
            + " |",
            "|---" + "|---:" * (3 * len(header)) + "|",
        ]
        for variable in COEF_ORDER:
            if not any(variable in columns[key]["coefficients"] for key in header):
                continue
            cells = [COEF_LABEL[variable]]
            for key in header:
                entry = columns[key]["coefficients"].get(variable, {})
                published_b, published_se = entry.get("published_b"), entry.get("published_se")
                replicated_b = entry.get("replicated_b")
                replicated_se = entry.get("replicated_se")
                cells += [
                    "--"
                    if published_b is None
                    else f"{published_b:+.4f} [{_fmt(published_se, 3)}]",
                    "--"
                    if replicated_b is None
                    else f"{replicated_b:+.4f} [{_fmt(replicated_se, 4)}]",
                    _fmt(entry.get("difference_in_se"), 2),
                ]
            lines.append("| " + " | ".join(cells) + " |")
        lines += [
            "",
            "| Statistic | " + " | ".join(f"({key}) pub | ({key}) rep" for key in header) + " |",
            "|---" + "|---:" * (2 * len(header)) + "|",
        ]
        for key_stat, label in STAT_LABELS.items():
            if not any(key_stat in columns[key]["stats"] for key in header):
                continue
            cells = [label]
            for key in header:
                entry = columns[key]["stats"].get(key_stat, {})
                digits = 0 if key_stat == "n_obs" else 4
                cells += [
                    _fmt(entry.get("published"), digits),
                    _fmt(entry.get("replicated"), digits),
                ]
            lines.append("| " + " | ".join(cells) + " |")

    lines += [
        "",
        "## Sensitivity: seasonality dummies",
        "",
        (
            "Main coefficients of Table 3 columns (1) and (2) with and without the 60 "
            "region x month seasonality dummies. The flight-level outlier threshold "
            "(ADR-0008) is fixed in a panel that arrives aggregated, so it is not varied here; "
            "the reconstruction pipeline is where that threshold is a parameter."
        ),
        "",
        "| Col | seasonality | N | HHI city-pair | HHI max endpoint | Adj. R-squared | J |",
        "|---:|---|---:|---:|---:|---:|---:|",
    ]
    for cell in grid.get("cells", []):
        stats = cell["stats"]
        lines.append(
            f"| ({cell['column']}) | {'yes' if cell['with_seasonality'] else 'no'} | "
            f"{stats['n_obs']:,} | "
            f"{cell['b'].get('rthhi', float('nan')):+.4f} "
            f"[{cell['se'].get('rthhi', float('nan')):.4f}] | "
            f"{cell['b'].get('maxcthhi', float('nan')):+.4f} "
            f"[{cell['se'].get('maxcthhi', float('nan')):.4f}] | "
            f"{stats['adj_r2']:.4f} | {stats['j_stat']:.4f} |"
        )
    return "\n".join(lines) + "\n"


def finite(payload: Any) -> Any:
    """Replace NaN and infinities with ``null``: strict JSON has no literal for them.

    `reports/replication.typ` parses these files with Typst's ``json()``, which
    rejects the ``NaN`` token Python's ``json`` is happy to emit.
    """
    if isinstance(payload, dict):
        return {key: finite(value) for key, value in payload.items()}
    if isinstance(payload, list):
        return [finite(value) for value in payload]
    if isinstance(payload, float) and not np.isfinite(payload):
        return None
    return payload


def dump(payload: Any) -> str:
    return json.dumps(finite(payload), indent=1, ensure_ascii=False, default=float) + "\n"
